readd github actions

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -1,30 +1,60 @@
-name: release
+name: Release
 
-on:
-    push:
-        tags:
-            - "*.*.*"
+on: create
 
 jobs:
     release:
-        name: Release
+        if: ${{ startsWith(github.ref, 'refs/heads/release/v') }}
         runs-on: ubuntu-latest
         steps:
-            - name: Checkout code
-              uses: actions/checkout@v3
-
-            - name: Set up Python 3.10
+            - name: Set up Python 3.9
               uses: actions/setup-python@v4
               with:
-                  python-version: "3.10"
+                  python-version: 3.9
 
-            - name: Install hatch
-              run: pip install hatch
+            - name: Extract the tag
+              id: vars
+              run: |
+                  echo "::set-output name=tag::${GITHUB_REF##*/}"
 
-            - name: Build project for distribution
-              run: hatch build
+            - name: Check tag validity
+              env:
+                  VERSION: ${{ steps.vars.outputs.tag }}
+              run: |
+                  grep "^v[[:digit:]]\.[[:digit:]]\.[[:digit:]]$" <<< "$VERSION" || (echo "Invalid version: '$VERSION'" && exit 42)
 
-            - name: Publish a Python distribution to PyPI
-              uses: pypa/gh-action-pypi-publish@release/v1
+            - name: Install dependencies
+              run: |
+                  sudo apt install pandoc
+                  python -m pip install --upgrade pip
+                  pip install tox bump2version
+                  pip install -e'.'
+
+            - name: Check generated docs
+              run: |
+                  tox -e check-docs
+
+            - name: Bump the version
+              # the part (patch) doesn't matter when supplying --new-version
+              env:
+                  VERSION: ${{ steps.vars.outputs.tag }}
+              run: |
+                  bump2version patch --no-commit --no-tag --verbose --new-version "${VERSION/v/}"
+
+            - name: Commit version bump
+              uses: stefanzweifel/git-auto-commit-action@v4
               with:
-                  password: ${{ secrets.PYPI_API_TOKEN }}
+                  file_pattern: setup.py squidpy/__init__.py .bumpversion.cfg
+                  commit_user_name: CI
+                  commit_message: ${{ format('[auto][ci skip] Release {0}', steps.vars.outputs.tag) }}
+                  tagging_message: ${{ steps.vars.outputs.tag }}
+                  skip_dirty_check: false
+
+            # `Test` triggers `Deployment`
+            # TODO(michalk8): can't find WD for `Test`
+            - name: Invoke deployment workflow
+              uses: benc-uk/workflow-dispatch@v1
+              with:
+                  workflow: Deployment
+                  token: ${{ secrets.RELEASE_DISPATCH_TOKEN }}
+                  inputs: '{ "reason": "release" }'
